config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Serve websocket cable requests in-process
  mount ActionCable.server => '/cable'
  root 'votes#new'
  
  resource 'vote', only: [:new, :create] do
    member do
      get :result
      get :red, path: 'view_red'
      get :white, path: 'view_white'

      get :settings, action: 'get_settings'
      post :settings, action: 'post_settings'
    end
  end
  

  


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include VoteHelper
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  layout "voting", :only => [:new]

  def result
  end

  def view_red
  end

  def view_white
  end

  def create
    ticket_id = params[:ticket_id].upcase
    team = params["team"]
    if start_voting?
      if check_id_valid?(ticket_id)
        if !check_voted?(ticket_id)
          if check_team_valid?(team)
            do_vote(ticket_id, team) 
            flash[:info] = "投票成功！"
            VoteResultChannel.send_result({ticket_id: ticket_id, team: team})
          else
            flash[:info] = "無效的選項，請選擇您想支持的隊伍"
          end
        else
          flash[:info] = "您已經投過票囉!"
        end
      else
        flash[:info] = "無效的票卷號碼"
      end
    else
      flash[:info] = "目前不在投票時間!"
    end
    redirect_to new_vote_path
  end

  def new
  end


  def get_settings
    time = REDIS.get("kga.start_vote_time")
    if time
      @start_time = Time.parse(time).strftime("%Y-%m-%dT%H:%M:%S")
    else
      @start_time = nil
    end
    time = REDIS.get("kga.end_vote_time")
    if time
      @end_time = Time.parse(time).strftime("%Y-%m-%dT%H:%M:%S")
    else
      @end_time = nil
    end

  end

  def post_settings
    case params["command"]
    when "reset"
      case params["commit"]
      when "重置全部"
        VoteHelper.reset_all
      when "票數歸零"
        VoteHelper.clear_vote
      when "清除投票紀錄"
        VoteHelper.reset_all_ticket
      end
    when "vote"
      if params["value"]
        val = session["value"] = params["value"].to_i
      else
        val = 0
      end
      case params["commit"]
      when "強制投紅組"
        VoteHelper.force_vote "red", val
      when "強制投白組"
        VoteHelper.force_vote "white", val
      when "隨機投票"
        VoteHelper.random_voting val
      end
    when "time"
      case params["commit"]
      when "設定"
        timeval = Time.parse(params["time"]).strftime("%Y-%m-%d %H:%M:%S")
      when "清除"
        timeval = nil
      end
      redis_key = "kga.#{params["time_type"]}_vote_time"
      if timeval
        REDIS.set(redis_key, timeval)
      else
        REDIS.del(redis_key)
      end
    end
    redirect_to settings_vote_path
  end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/vote_helper.rb
module VoteHelper


  def self.get_vote_result
    {
      type: 'result',
      red: REDIS.get("vote_result.red").to_i,
      white: REDIS.get("vote_result.white").to_i,
    }
  end


  def check_id_valid?(ticket_id)
    !REDIS.hget("ticket_info",ticket_id).nil?
  end

  def check_voted?(ticket_id)
    state = REDIS.hget("ticket_info",ticket_id)
    state && !state.empty?
  end

  def check_team_valid?(team)
    ["red","white"].include? team
  end

  def start_voting?
    start_time = REDIS.get("kga.start_vote_time")
    if start_time
      start_time = Time.parse(start_time)
    else
      start_time = Time.new(2000,5,25,18,30)
    end
    end_time = REDIS.get("kga.end_vote_time")
    if end_time
      end_time = Time.parse(end_time)
    else
      end_time = Time.new(2020,5,25,20,30)
    end
    now = Time.now
    return now >= start_time && now <= end_time
  end

  # team should be either "red" or "white"
  # assume ticket_id is valid and not voted
  def do_vote(ticket_id,team)
    # record as vote
    REDIS.hset("ticket_info",ticket_id,team)
    # vote it!
    REDIS.incr("vote_result.#{team}")
  end

  def vote_result_name(name)
    case name
    when "red"
      "紅組"
    when "white"
      "白組"
    else
      "未投票"
    end
  end

  # ==admin==
  def self.reset_all
    reset_all_ticket
    clear_vote
  end

  def self.clear_vote
    REDIS.multi do |multi|
      REDIS.set("vote_result.red",0)
      REDIS.set("vote_result.white",0)
    end
    VoteResultChannel.send_result
  end


  def self.reset_all_ticket
    REDIS.multi do |multi|
      # clear redis
      multi.del("ticket_info")
      # setup tickets
      generate_ticket_id.each do |ticket_id|
        multi.hset("ticket_info",ticket_id,"") # not voted
      end  
    end
  end

  def self.generate_ticket_id
    #return TICKET_LIST
    # FIXME! for test
    arr = []
    676.times do |i|
      arr << sprintf("%06d",i+1)
    end
    return arr
  end

  # for testing
  def self.force_vote(team,val = 1)
    REDIS.incrby("vote_result.#{team}",val)
    VoteResultChannel.send_result({:team => team, :ticket_id => sprintf("000%03d",rand(999)) } )
  end

  def self.random_voting(count = 100)
    count.times do 
      force_vote(["red","white"].sample,1)
      sleep (rand / 2)
    end
  end

  def self.voting_state(ticket_id = nil)
    if ticket_id
      REDIS.hget("ticket_info",ticket_id)
    else
      REDIS.hkeys("ticket_info").collect do |key|
        [key,voting_state(key)]
      end.sort_by {|data| data[0]}
    end
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>KgaVote</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => 'reload' %>


    <%= stylesheet_link_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css' %>
    <%= javascript_include_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/voting.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>KgaVote</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => 'reload' %>
    <%= javascript_include_tag 'voting_page', 'data-turbolinks-track' => 'reload' %>


    <%= stylesheet_link_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css' %>
    <%= javascript_include_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/vote/new.html.erb
<div class="vote-wrapper">
  <%= form_tag create_vote_path, method: :post  do %>
    <%= label 'ticket_id', "雄友之夜投票系統"%><br>
    <%= label 'ticket_id', "請輸入票卷上的流水號"%><br>
    <%= text_field_tag 'ticket_id',nil,placeholder: '完整流水號' %><br>
    <%= label 'ticket_id', "請選擇想支持的隊伍"%><br>
    <div class="team-group">
      <a class="team-field-link" href="#"><div class="team-field red" data-team="red">紅組</div></a>
      <a class="team-field-link" href="#"><div class="team-field white" data-team="white">白組</div></a>
      <%= hidden_field_tag 'team', 'no-select', class: "team-select" %><br>
      <%= submit_tag "送出", class: "btn btn-primary btn-lg btn-block submit"%>
    </div>
  <% end %>
  <p class="flash"><%= flash[:info] %></p>
  <p style="font-size: 16px;color: #aaa;">Author: <a href="https://www.facebook.com/computerhenry321">Liang-Chi Tseng (曾亮齊)</a></p>
</div>

app/views/votes/get_settings.html.erb
<div class="container">
  <h2>投票操作</h2>
  <%= form_tag settings_vote_path, method: 'post' do %>
    <%= hidden_field_tag "command", "vote" %>
    <p><%= number_field_tag "value", session["value"], placeholder: "操作票數" %></p>
    <%= submit_tag "強制投紅組", class: "btn btn-primary btn-lg" %>
    <%= submit_tag "強制投白組", class: "btn btn-primary btn-lg" %>
    <%= submit_tag "隨機投票", class: "btn btn-primary btn-lg" %>
  <% end %>
  <h2>重置操作</h2>
  <%= form_tag settings_vote_path, method: 'post' do %>
    <%= hidden_field_tag "command", "reset" %>
    <%= submit_tag "重置全部", class: "btn btn-danger btn-lg"%>
    <%= submit_tag "票數歸零", class: "btn btn-warning btn-lg"%>
    <%= submit_tag "清除投票紀錄", class: "btn btn-warning btn-lg"%>
  <% end %>
  <h2>設定投票開始時間</h2>
  <%= form_tag settings_vote_path, method: 'post' do %>
    <%= hidden_field_tag "command", "time" %>
    <%= hidden_field_tag "time_type", "start" %>
    <p>
    <% if !@start_time %>
      無設定起始時間，預設為2000-05-25
    <% end %>
    </p>
    <p>
    <%= datetime_local_field_tag "time", @start_time %>
    </p>
    <%= submit_tag "設定", class: "btn btn-primary btn-lg"%>
    <%= submit_tag "清除", class: "btn btn-warning btn-lg"%>
  <% end %>
  <h2>設定投票結束時間</h2>
  <%= form_tag settings_vote_path, method: 'post' do %>
    <%= hidden_field_tag "command", "time" %>
    <%= hidden_field_tag "time_type", "end" %>
    <p>
    <% if !@end_time %>
      無設定結束時間，預設為2020-05-25
    <% end %>
    </p>
    <p>
    <%= datetime_local_field_tag "time", @end_time %>
    </p>
    <%= submit_tag "設定", class: "btn btn-primary btn-lg"%>
    <%= submit_tag "清除", class: "btn btn-warning btn-lg"%>
  <% end %>

  <h2>投票紀錄</h2>
  <table class="table">
    <tr>
      <th>流水號</th>
      <th>投票組別</th>
    </tr>
    <% VoteHelper.voting_state.each do |entry| %>
      <tr>
        <td><%= entry[0] %></td>
        <td><%= vote_result_name(entry[1]) %></td>
      </tr>
    <% end %>
  </table>



</div>

app/views/votes/new.html.erb
<div class="vote-wrapper">
  <%= form_tag vote_path, method: :post  do %>
    <%= label 'ticket_id', "雄友之夜投票系統"%><br>
    <%= label 'ticket_id', "請輸入票卷上的流水號"%><br>
    <%= text_field_tag 'ticket_id',nil,placeholder: '完整流水號' %><br>
    <%= label 'ticket_id', "請選擇想支持的隊伍"%><br>
    <div class="team-group">
      <a class="team-field-link" href="#"><div class="team-field red" data-team="red">紅組</div></a>
      <a class="team-field-link" href="#"><div class="team-field white" data-team="white">白組</div></a>
      <%= hidden_field_tag 'team', 'no-select', class: "team-select" %><br>
      <%= submit_tag "送出", class: "btn btn-primary btn-lg btn-block submit"%>
    </div>
  <% end %>
  <p class="flash"><%= flash[:info] %></p>
  <p style="font-size: 16px;color: #aaa;">Author: <a href="https://www.facebook.com/computerhenry321">Liang-Chi Tseng (曾亮齊)</a></p>
</div>

app/views/votes/result.html.erb
<div class="counter-group red">
  <h2>紅組</h2>
  <div id="red-counter"></div>
  <div class="voter"></div>
</div>
<div class="counter-group white">
  <h2>白組</h2>
  <div id="white-counter"></div>
  <div class="voter"></div>
</div>

app/views/votes/view_red.html.erb
<div class="counter-group red" id="single">
  <h2>紅組</h2>
  <div id="red-counter"></div>
  <div class="voter"></div>
</div>

app/views/votes/view_white.html.erb
<div class="counter-group white" id="single">
  <h2>白組</h2>
  <div id="white-counter"></div>
  <div class="voter"></div>
</div>